import {
  collection, doc, getDoc, getDocs, setDoc, updateDoc, deleteDoc,
  query, where, serverTimestamp, writeBatch, Timestamp, orderBy
} from "firebase/firestore";
import { db, auth } from "./firebase";
import type { AppUser, License, ResellerProfile, UserStatus, FeatureFlags, HwidData, Announcement } from "./types";
import { DEFAULT_RESELLER_PERMISSIONS } from "./types";

// ── Helpers ──
const ts = (t: Timestamp | null | undefined): string => {
  if (!t) return "—";
  if (t.toDate) return t.toDate().toLocaleString();
  return String(t);
};

function randomSegment(len: number): string {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  let s = "";
  for (let i = 0; i < len; i++) s += chars[Math.floor(Math.random() * chars.length)];
  return s;
}

// ══════════════════════════════════════════════════════
//  RESELLER AUTH — find own reseller doc by UID,
//  if not found by UID, query by email & migrate
//  the doc to resellers/{uid} so Firestore rules
//  (isActiveReseller) always work from that point on.
// ══════════════════════════════════════════════════════

function parseProfile(id: string, data: Record<string, unknown>): ResellerProfile {
  return {
    ...data,
    id,
    permissions: data.permissions
      ? { ...DEFAULT_RESELLER_PERMISSIONS, ...(data.permissions as object) }
      : DEFAULT_RESELLER_PERMISSIONS,
  } as ResellerProfile;
}

export async function fetchMyResellerProfile(): Promise<ResellerProfile | null> {
  const user = auth.currentUser;
  if (!user?.email) return null;

  // 1️⃣  Fast path — UID-keyed doc already exists (normal after first login)
  try {
    const snap = await getDoc(doc(db, "resellers", user.uid));
    if (snap.exists()) {
      return parseProfile(snap.id, snap.data() as Record<string, unknown>);
    }
  } catch { /* may not exist yet */ }

  // 2️⃣  Fallback — query by email (first-ever login for this reseller)
  const q = query(
    collection(db, "resellers"),
    where("email", "==", user.email.toLowerCase())
  );
  const snap = await getDocs(q);
  if (snap.empty) return null;

  const oldDoc = snap.docs[0];
  const data = oldDoc.data();

  // 3️⃣  Migrate: copy data to resellers/{uid} then delete old auto-ID doc
  //     This ensures isActiveReseller() + counter updates work via UID path.
  try {
    await setDoc(doc(db, "resellers", user.uid), {
      ...data,
      // make sure email is lowercase just in case
      email: user.email.toLowerCase(),
    });
    // Delete the old auto-ID doc (now redundant)
    if (oldDoc.id !== user.uid) {
      await deleteDoc(doc(db, "resellers", oldDoc.id));
    }
    return parseProfile(user.uid, data as Record<string, unknown>);
  } catch {
    // If migration fails (permissions), still return the profile from the old doc
    return parseProfile(oldDoc.id, data as Record<string, unknown>);
  }
}

// ══════════════════════════════════════════════════════
//  USERS — only users who redeemed a license
//  generated by this reseller (not all users)
// ══════════════════════════════════════════════════════

export async function fetchUsers(
  perms: ResellerProfile["permissions"],
  generatedCodes: string[],
): Promise<AppUser[]> {
  if (generatedCodes.length === 0) return [];

  // 1️⃣  Find which of our generated codes have been redeemed (have a uid)
  const redeemedUids = new Set<string>();
  const codeToUid = new Map<string, string>();

  const chunks: string[][] = [];
  for (let i = 0; i < generatedCodes.length; i += 30) {
    chunks.push(generatedCodes.slice(i, i + 30));
  }
  for (const chunk of chunks) {
    const q = query(collection(db, "licenses"), where("__name__", "in", chunk));
    const snap = await getDocs(q);
    snap.forEach(d => {
      const l = d.data();
      if (l.uid) {
        redeemedUids.add(l.uid);
        codeToUid.set(d.id, l.uid);
      }
    });
  }

  if (redeemedUids.size === 0) return [];

  // 2️⃣  Fetch only those user documents
  const users: AppUser[] = [];
  for (const uid of redeemedUids) {
    try {
      const userSnap = await getDoc(doc(db, "users", uid));
      if (!userSnap.exists()) continue;
      const u = userSnap.data();

      let features: FeatureFlags = { bypass: false, streamerMode: false, formBypass: false, stopNetwork: false };
      if (perms.visibility.features) {
        try {
          const fs = await getDoc(doc(db, "users", uid, "features", "flags"));
          if (fs.exists()) features = { ...features, ...fs.data() } as FeatureFlags;
        } catch {}
      }

      let hwid: HwidData = {};
      if (perms.visibility.hwid) {
        try {
          const hs = await getDoc(doc(db, "users", uid, "hwid", "data"));
          if (hs.exists()) hwid = hs.data() as HwidData;
        } catch {}
      }

      users.push({
        uid,
        email: perms.visibility.email ? (u.email || "") : "••••••••",
        licensed: !!u.licensed,
        licenseCode: perms.visibility.licenseCode ? (u.licenseCode || "") : "",
        features,
        hwid,
        status: (u.status as UserStatus) || "active",
        deactivatedAt: u.deactivatedAt || undefined,
        suspendedAt: u.suspendedAt || undefined,
        bannedAt: u.bannedAt || undefined,
      });
    } catch {}
  }
  return users;
}

export async function fetchUserDetail(uid: string, perms: ResellerProfile["permissions"]): Promise<AppUser> {
  const userSnap = await getDoc(doc(db, "users", uid));
  if (!userSnap.exists()) throw new Error("User not found");
  const u = userSnap.data();

  let features: FeatureFlags = { bypass: false, streamerMode: false, formBypass: false, stopNetwork: false };
  if (perms.visibility.features) {
    try {
      const fs = await getDoc(doc(db, "users", uid, "features", "flags"));
      if (fs.exists()) features = { ...features, ...fs.data() } as FeatureFlags;
    } catch {}
  }

  let hwid: HwidData = {};
  if (perms.visibility.hwid) {
    try {
      const hs = await getDoc(doc(db, "users", uid, "hwid", "data"));
      if (hs.exists()) hwid = hs.data() as HwidData;
    } catch {}
  }

  return {
    uid,
    email: perms.visibility.email ? (u.email || "") : "••••••••",
    licensed: !!u.licensed,
    licenseCode: perms.visibility.licenseCode ? (u.licenseCode || "") : "",
    features,
    hwid,
    status: (u.status as UserStatus) || "active",
    deactivatedAt: u.deactivatedAt || undefined,
    suspendedAt: u.suspendedAt || undefined,
    bannedAt: u.bannedAt || undefined,
  };
}

// ══════════════════════════════════════════════════════
//  FEATURE TOGGLES (only if permitted)
// ══════════════════════════════════════════════════════

export async function toggleFeature(uid: string, key: string, value: boolean) {
  await setDoc(doc(db, "users", uid, "features", "flags"), { [key]: value }, { merge: true });
}

// ══════════════════════════════════════════════════════
//  USER ACTIONS (only if permitted)
// ══════════════════════════════════════════════════════

export async function deactivateUser(uid: string) {
  await updateDoc(doc(db, "users", uid), {
    status: "deactivated",
    deactivatedAt: new Date().toISOString(),
  });
  await setDoc(doc(db, "users", uid, "features", "flags"), {
    bypass: false, streamerMode: false, formBypass: false, stopNetwork: false,
  });
}

export async function reactivateUser(uid: string) {
  await updateDoc(doc(db, "users", uid), {
    status: "active",
    deactivatedAt: "",
  });
}

export async function suspendUser(uid: string) {
  const userSnap = await getDoc(doc(db, "users", uid));
  const userData = userSnap.data();
  if (userData?.licenseCode) {
    try {
      await updateDoc(doc(db, "licenses", userData.licenseCode), { uid: "", redeemedAt: null });
    } catch {}
  }
  await updateDoc(doc(db, "users", uid), {
    status: "suspended",
    suspendedAt: new Date().toISOString(),
    licensed: false,
    licenseCode: "",
  });
  await setDoc(doc(db, "users", uid, "features", "flags"), {
    bypass: false, streamerMode: false, formBypass: false, stopNetwork: false,
  });
}

export async function unsuspendUser(uid: string) {
  await updateDoc(doc(db, "users", uid), {
    status: "active",
    suspendedAt: "",
  });
}

export async function revokeLicense(uid: string) {
  const userSnap = await getDoc(doc(db, "users", uid));
  const userData = userSnap.data();
  if (userData?.licenseCode) {
    await updateDoc(doc(db, "licenses", userData.licenseCode), { uid: "", redeemedAt: null });
  }
  await updateDoc(doc(db, "users", uid), { licensed: false, licenseCode: "" });
}

// ══════════════════════════════════════════════════════
//  HWID RESETS (only if permitted)
// ══════════════════════════════════════════════════════

export async function triggerWindowsReset(uid: string) {
  await setDoc(doc(db, "users", uid, "hwid", "data"), { windowsReset: true }, { merge: true });
}

export async function triggerFullAccountReset(uid: string) {
  // 1. Revoke license
  const userSnap = await getDoc(doc(db, "users", uid));
  const userData = userSnap.data();
  if (userData?.licenseCode) {
    try {
      await updateDoc(doc(db, "licenses", userData.licenseCode), { uid: "", redeemedAt: null });
    } catch {}
  }

  // 2. Wipe HWID
  try { await deleteDoc(doc(db, "users", uid, "hwid", "data")); } catch {}

  // 3. Reset features
  await setDoc(doc(db, "users", uid, "features", "flags"), {
    bypass: false, streamerMode: false, formBypass: false, stopNetwork: false,
  });

  // 4. Reset user doc
  await updateDoc(doc(db, "users", uid), {
    licensed: false,
    licenseCode: "",
  });
}

// ══════════════════════════════════════════════════════
//  LICENSE GENERATION
// ══════════════════════════════════════════════════════

export async function fetchMyLicenses(generatedCodes: string[]): Promise<License[]> {
  if (generatedCodes.length === 0) return [];

  // Firestore 'in' queries support max 30 items at a time
  const licenses: License[] = [];
  const chunks: string[][] = [];
  for (let i = 0; i < generatedCodes.length; i += 30) {
    chunks.push(generatedCodes.slice(i, i + 30));
  }

  for (const chunk of chunks) {
    const q = query(collection(db, "licenses"), where("__name__", "in", chunk));
    const snap = await getDocs(q);
    snap.forEach(d => {
      const l = d.data();
      licenses.push({ ...l, code: d.id } as License);
    });
  }

  return licenses;
}

export async function generateLicenses(
  resellerId: string,
  count: number,
  plan: "trial" | "permanent",
  prefix: string,
  currentKeysUsed: number,
  currentCodes: string[],
  trialDays?: number,
  kernelAccess: boolean = true,
): Promise<string[]> {
  const codes: string[] = [];
  const batch = writeBatch(db);

  for (let i = 0; i < count; i++) {
    const code = `${prefix}-${randomSegment(4)}-${randomSegment(4)}-${randomSegment(4)}`;
    codes.push(code);
    const data: Record<string, unknown> = {
      active: true,
      uid: "",
      plan,
      createdAt: serverTimestamp(),
      redeemedAt: null,
      generatedBy: resellerId,
      kernelAccess,
    };
    if (plan === "trial" && trialDays) data.trialDays = trialDays;
    batch.set(doc(db, "licenses", code), data);
  }

  await batch.commit();

  // Update own reseller counters (allowed by Firestore rules)
  await updateDoc(doc(db, "resellers", resellerId), {
    keysUsed: currentKeysUsed + count,
    generatedCodes: [...currentCodes, ...codes],
    lastActivity: serverTimestamp(),
  });

  return codes;
}

export { ts };

// ══════════════════════════════════════════════════════
//  ANNOUNCEMENTS (read-only for resellers)
// ══════════════════════════════════════════════════════

export async function fetchAnnouncements(): Promise<Announcement[]> {
  const q = query(collection(db, "announcements"), orderBy("createdAt", "desc"));
  const snap = await getDocs(q);
  return snap.docs.map(d => ({ id: d.id, ...d.data() }) as Announcement);
}
